// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: api/modelop/service/v1/modelop.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateModelopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateModelopRequest) Reset() {
	*x = CreateModelopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModelopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelopRequest) ProtoMessage() {}

func (x *CreateModelopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelopRequest.ProtoReflect.Descriptor instead.
func (*CreateModelopRequest) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{0}
}

type CreateModelopReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateModelopReply) Reset() {
	*x = CreateModelopReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModelopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelopReply) ProtoMessage() {}

func (x *CreateModelopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelopReply.ProtoReflect.Descriptor instead.
func (*CreateModelopReply) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{1}
}

type UpdateModelopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateModelopRequest) Reset() {
	*x = UpdateModelopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelopRequest) ProtoMessage() {}

func (x *UpdateModelopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelopRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelopRequest) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{2}
}

type UpdateModelopReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateModelopReply) Reset() {
	*x = UpdateModelopReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelopReply) ProtoMessage() {}

func (x *UpdateModelopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelopReply.ProtoReflect.Descriptor instead.
func (*UpdateModelopReply) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{3}
}

type DeleteModelopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteModelopRequest) Reset() {
	*x = DeleteModelopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteModelopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelopRequest) ProtoMessage() {}

func (x *DeleteModelopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelopRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelopRequest) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{4}
}

type DeleteModelopReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteModelopReply) Reset() {
	*x = DeleteModelopReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteModelopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelopReply) ProtoMessage() {}

func (x *DeleteModelopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelopReply.ProtoReflect.Descriptor instead.
func (*DeleteModelopReply) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{5}
}

type GetModelopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetModelopRequest) Reset() {
	*x = GetModelopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelopRequest) ProtoMessage() {}

func (x *GetModelopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelopRequest.ProtoReflect.Descriptor instead.
func (*GetModelopRequest) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{6}
}

type GetModelopReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetModelopReply) Reset() {
	*x = GetModelopReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelopReply) ProtoMessage() {}

func (x *GetModelopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelopReply.ProtoReflect.Descriptor instead.
func (*GetModelopReply) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{7}
}

type ListModelopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListModelopRequest) Reset() {
	*x = ListModelopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModelopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelopRequest) ProtoMessage() {}

func (x *ListModelopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelopRequest.ProtoReflect.Descriptor instead.
func (*ListModelopRequest) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{8}
}

type ListModelopReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListModelopReply) Reset() {
	*x = ListModelopReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModelopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelopReply) ProtoMessage() {}

func (x *ListModelopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_modelop_service_v1_modelop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelopReply.ProtoReflect.Descriptor instead.
func (*ListModelopReply) Descriptor() ([]byte, []int) {
	return file_api_modelop_service_v1_modelop_proto_rawDescGZIP(), []int{9}
}

var File_api_modelop_service_v1_modelop_proto protoreflect.FileDescriptor

var file_api_modelop_service_v1_modelop_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x16,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x91, 0x04, 0x0a, 0x07, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x69, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x69, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x6f, 0x70, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x2c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x5e,
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x79, 0x74, 0x65, 0x66, 0x6c, 0x6f, 0x77, 0x74,
	0x65, 0x61, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x76, 0x75, 0x65, 0x2d, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_modelop_service_v1_modelop_proto_rawDescOnce sync.Once
	file_api_modelop_service_v1_modelop_proto_rawDescData = file_api_modelop_service_v1_modelop_proto_rawDesc
)

func file_api_modelop_service_v1_modelop_proto_rawDescGZIP() []byte {
	file_api_modelop_service_v1_modelop_proto_rawDescOnce.Do(func() {
		file_api_modelop_service_v1_modelop_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_modelop_service_v1_modelop_proto_rawDescData)
	})
	return file_api_modelop_service_v1_modelop_proto_rawDescData
}

var file_api_modelop_service_v1_modelop_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_modelop_service_v1_modelop_proto_goTypes = []interface{}{
	(*CreateModelopRequest)(nil), // 0: api.modelop.service.v1.CreateModelopRequest
	(*CreateModelopReply)(nil),   // 1: api.modelop.service.v1.CreateModelopReply
	(*UpdateModelopRequest)(nil), // 2: api.modelop.service.v1.UpdateModelopRequest
	(*UpdateModelopReply)(nil),   // 3: api.modelop.service.v1.UpdateModelopReply
	(*DeleteModelopRequest)(nil), // 4: api.modelop.service.v1.DeleteModelopRequest
	(*DeleteModelopReply)(nil),   // 5: api.modelop.service.v1.DeleteModelopReply
	(*GetModelopRequest)(nil),    // 6: api.modelop.service.v1.GetModelopRequest
	(*GetModelopReply)(nil),      // 7: api.modelop.service.v1.GetModelopReply
	(*ListModelopRequest)(nil),   // 8: api.modelop.service.v1.ListModelopRequest
	(*ListModelopReply)(nil),     // 9: api.modelop.service.v1.ListModelopReply
}
var file_api_modelop_service_v1_modelop_proto_depIdxs = []int32{
	0, // 0: api.modelop.service.v1.Modelop.CreateModelop:input_type -> api.modelop.service.v1.CreateModelopRequest
	2, // 1: api.modelop.service.v1.Modelop.UpdateModelop:input_type -> api.modelop.service.v1.UpdateModelopRequest
	4, // 2: api.modelop.service.v1.Modelop.DeleteModelop:input_type -> api.modelop.service.v1.DeleteModelopRequest
	6, // 3: api.modelop.service.v1.Modelop.GetModelop:input_type -> api.modelop.service.v1.GetModelopRequest
	8, // 4: api.modelop.service.v1.Modelop.ListModelop:input_type -> api.modelop.service.v1.ListModelopRequest
	1, // 5: api.modelop.service.v1.Modelop.CreateModelop:output_type -> api.modelop.service.v1.CreateModelopReply
	3, // 6: api.modelop.service.v1.Modelop.UpdateModelop:output_type -> api.modelop.service.v1.UpdateModelopReply
	5, // 7: api.modelop.service.v1.Modelop.DeleteModelop:output_type -> api.modelop.service.v1.DeleteModelopReply
	7, // 8: api.modelop.service.v1.Modelop.GetModelop:output_type -> api.modelop.service.v1.GetModelopReply
	9, // 9: api.modelop.service.v1.Modelop.ListModelop:output_type -> api.modelop.service.v1.ListModelopReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_modelop_service_v1_modelop_proto_init() }
func file_api_modelop_service_v1_modelop_proto_init() {
	if File_api_modelop_service_v1_modelop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_modelop_service_v1_modelop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModelopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModelopReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelopReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteModelopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteModelopReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelopReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListModelopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_modelop_service_v1_modelop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListModelopReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_modelop_service_v1_modelop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_modelop_service_v1_modelop_proto_goTypes,
		DependencyIndexes: file_api_modelop_service_v1_modelop_proto_depIdxs,
		MessageInfos:      file_api_modelop_service_v1_modelop_proto_msgTypes,
	}.Build()
	File_api_modelop_service_v1_modelop_proto = out.File
	file_api_modelop_service_v1_modelop_proto_rawDesc = nil
	file_api_modelop_service_v1_modelop_proto_goTypes = nil
	file_api_modelop_service_v1_modelop_proto_depIdxs = nil
}
